run:
  timeout: 2m
  modules-download-mode: vendor
linters:
  enable:
    - revive
    - gofmt
linters-settings:
  revive:
    # severity: warning
    rules:
      - name: package-comments
        disabled: true
issues:
  exclude-use-default: false
