name: "Continuous Integration"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          with:
            cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint
        run: make lint
      - name: Secure dockerfile
        run: make dockerfile-security
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          with:
            cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Unit Tests
        run: make test
